### ISSUE TITLE
Installing sailor multiple times / updating will cause app files to be duplicated

### ISSUE THREAD

**Issue by Etiene** [sailorproject/sailor#138] opened 2016-10-12 14:30 UTC
When installing sailor if you have sailor already installed, some files inside the `src/sailor/blank-app` will be duplicated because LuaRocks does not remove them previously to installing a new version of sailor. 
Example:
```
.htaccess
.htaccess~
.htaccess~~
.htaccess~~~
```

How to reproduce: Go to `/rockspecs/` then `luarocks install <rockspec file name>` with two different versions of sailor

**Comment by Etiene** [comment] 2016-10-12 14:36
@hishamhm help? :)

**Comment by mpeterv** [comment] 2016-10-12 15:49
On a fresh installation of Lua 5.2 and Luarocks 2.4.1 in directory `t` after installing sailor 0.5-3:

* `t/share/lua/5.2/sailor/blank-app/` contains `.htaccess`.
* Manifest for sailor modules contains `["sailor/blank-app/.htaccess"] = "sailor/blank-app/.htaccess"`.
* Rock manifest contains `sailor["blank-app"][".htaccess"] = "a5bb108e6579e61043b2602923f0aea3"`.

Installing sailor 0.5-4 prints `Warning: /home/mpeterv/sailor/t/share/lua/5.2/sailor/blank-app/.htaccess is not tracked by this installation of LuaRocks. Moving it to /home/mpeterv/sailor/t/share/lua/5.2/sailor/blank-app/.htaccess~` plus similar errors for other files mentioned in the rockspec in `install.lua` table.

After installing sailor 0.5-4:

* `t/share/lua/5.2/sailor/blank-app/` contains `.htaccess~` but not  `.htaccess`.
* It appears that none of files from `install.lua` are actually installed anywhere.
* Manifest and rock manifest are not changed except sailor version.

Looks like a bug in Luarocks =(

**Comment by hishamhm** [comment] 2016-10-12 19:37
@mpeterv Thank you for hunting it down! I'm wondering how could we write a test to catch that and avoid a regression.

**Comment by Etiene** [comment] 2016-10-12 19:43
@mpeterv oh, this is awesome! I'll consider this fixed then. Will be ok on future luarocks versions :)

**Closed** 2016-10-12 20:23 UTC
Labels: bug
