### ISSUE TITLE
Verify form file input uploading on Xavante webserver

### ISSUE THREAD

**Issue by Etiene** [sailorproject/sailor#74] opened 2016-02-01 06:18 UTC

**Comment by xspager** [comment] 2016-02-09 05:28
I'm having a hard time figuring out why but since what I already figure out can be helpful... The only example of upload I found is the one in https://github.com/sailorproject/sailor/blob/master/test/dev-app/controllers/test.lua#L192 and it expect page.POST.datafile to be a file but it is actually a table like
{
    ["content-type"] = "application/octet-stream",
    file = filehandler,
    filename = " my_file.txt",
    file size = 42
}

**Comment by xspager** [comment] 2016-02-09 15:47
Ok, now I got it. Mod_lua set a entry on table "POST" with a "string" when it finds a file field on the post but CGILua set a table with the data I mentioned before. You could use page.POST.form_file_field.file:read("*a") to read the file as a "string" or doing something else.

**Comment by xspager** [comment] 2016-03-05 15:48
What it takes to close this issue?

**Comment by m1cr0man** [comment] 2016-05-02 13:23
From what I've been testing in Xavante, CGILua handles files weirdly.

You got the format of the table right for one file, but when multiple files are uploaded their data is appended in similarly formatted tables indexed in an array fashion. Here's an example uploading 3 files:
```Lua
{
["content-type"] = "application/octet-stream",
file = filehandler,
filename = " my_file_a.txt",
file size = 42,
[1] = {
  ["content-type"] = "application/octet-stream",
  file = filehandler,
  filename = " my_file_b.txt",
  file size = 96
},
[2] = {
  ["content-type"] = "application/octet-stream",
  file = filehandler,
  filename = " my_file_c.txt",
  file size = 256
}
}
```
As you can see, the extra files are stuck onto the value as if they were some attribute of the first file received. In my opinion, it would more logical to put every file into its own table. The problem is this is done in CGILua and not Remy/Sailor so any fix would kind of be a hack, because we would just be pushing stuff around before the user/developer gets their hands on it.

Another solution would be to handle the request data ourselves like I already did for Nginx. This way we can standardise file uploading across all servers, and add/remove features as we need them. For example, none of the Lua frameworks support chunked uploads out of the box, and this may be something people want from Sailor in the future.

**Closed** 2016-10-04 19:55 UTC
