### ISSUE TITLE
Sailor not installing on Linux Mint 17.3

### ISSUE THREAD

**Issue by Hygens** [sailorproject/sailor#88] opened 2016-02-21 16:00 UTC
I have followed all steps for installing Sailor as for Ubuntu but I reached that error:

josenildo@josenildo-Dell ~ $ luarocks install sailor

Error: No results matching query were found.

Attached is image for that.

![captura de tela de 2016-02-21 12 58 25](https://cloud.githubusercontent.com/assets/5247983/13203616/d14ff426-d89a-11e5-8b0d-7bc2f7444500.png)

I have installed with that command:
luarocks install https://luarocks.org/manifests/etiene/sailor-0.5-4.rockspec

**Comment by felipedaragon** [comment] 2016-02-21 17:34
Tried to reproduce this in Mint 17.1 Cinnamon 32bit. I was able to install luarocks after making a sudo apt-get update. But then when calling luarocks install sailor I run into something different:
(...)
cp: cannot stat ‘valua.lua’: No such file or directory

Error: Failed installing dependency: http://luarocks.org/repositories/rocks/valua-0.3-1.src.rock - Failed copying valua.lua

**Comment by Etiene** [comment] 2016-02-21 18:26
What's your Lua version?

**Comment by Hygens** [comment] 2016-02-21 18:44
I have installed lua5.2.4.

Em 21/02/2016 15:26, Etiene Dalcol escreveu:

**Comment by Hygens** [comment] 2016-02-21 18:46
Detail I'm using Linux Mint 17.3 x64 with compatbility libraries i386.

Em 21/02/2016 15:26, Etiene Dalcol escreveu:

**Comment by Hygens** [comment] 2016-02-21 19:18
Hi, Felipe!

I have tested on other machine with same linux mint 17.3 and after 
update really not function more.
I will be test on pure Ubuntu version if resolve the problem I will be 
using that environment for tests
with LUA.
If you found one solution for that problem tell me please.

Thank you,
Hygens

Em 21/02/2016 14:34, Felipe Daragon escreveu:

**Comment by Etiene** [comment] 2016-02-21 19:49
I don't have Linux mint here for testing. But that message is usually the output when installing sailor on verion 5.3, which sailor is not compatible with. Please do a lua --version again just to be sure?

Also can you try installing sailor directly from the src.rock? 

```
luarocks install https://luarocks.org/manifests/etiene/sailor-0.5-4.src.rock
```

**Comment by felipedaragon** [comment] 2016-02-21 20:14
That could explain the different results. My Mind box is using Lua 5.1.5 (according to lua -v

**Comment by Hygens** [comment] 2016-02-21 20:20
Hi, Felipe.

The correct version installed is 5.2.3 not 5.2.4 as attached image.
The error is that commented.
I will be testing on Ubuntu 16.04(LTS).
If you desire can close that issue.
If not functioning  on Ubuntu I will be testing with other framework.

Thank you,
Hygens

**Comment by felipedaragon** [comment] 2016-02-21 20:22
Etiene - I tried the luarocks install https://luarocks.org/manifests/etiene/sailor-0.5-4.src.rock and still got the same valua error. Weird

**Comment by Etiene** [comment] 2016-02-21 20:35
What's your luarocks version?

```luarocks --version```

**Comment by felipedaragon** [comment] 2016-02-21 20:35
Could it be this value within the rockspec?
         valua = "valua.lua"
which should perhaps be valua = "valua/valua.lua"?

**Comment by felipedaragon** [comment] 2016-02-21 20:35
luarocks 2.0.8

**Comment by Etiene** [comment] 2016-02-21 20:37
That is a very old version, please try updating luarocks first before we continue to narrow down the issue.

**Comment by Etiene** [comment] 2016-02-21 20:50
Also please type only ```luarocks```
It will show some information and at the end it shows which lua version it is using. You may have multiple lua versions installed and something is misconfigured

```
CONFIGURATION
	Lua version: 5.1
	Configuration files:
```

**Comment by Etiene** [comment] 2016-02-21 20:52
Also @felipedaragon, maybe you should open a different issue. You clearly do not have the same problem as the OP

**Comment by felipedaragon** [comment] 2016-02-21 20:56
Done - created the different issue.

@Hygens, which luarocks version do you have in your box?

**Comment by Hygens** [comment] 2016-02-21 21:05
That:
luarocks --version
luarocks 2.0.8
LuaRocks main command-line interface

**Comment by felipedaragon** [comment] 2016-02-21 21:07
We're both with outdated luarocks! :)

**Comment by Etiene** [comment] 2016-02-21 21:09
@Hygens please update it first before we narrow this down since this is a very old luarocks version :+1:

**Comment by felipedaragon** [comment] 2016-02-21 21:22
If you manage to upgrade it please let me know which commands you used

**Comment by felipedaragon** [comment] 2016-02-21 22:43
@Hygens I was able to upgrade luarocks and install Sailor after making the cleanup Hisham suggested at https://github.com/keplerproject/luarocks/issues/505

**Comment by Hygens** [comment] 2016-02-21 23:54
Felipe,

My steps:

1) Create folder on /usr/local/lua-rocks and execute sudo chown -R 
<user>.<user>  /usr/local/lua-rocks(This is your prefix).  <user>=Your 
logged user.
2) Get source from lua5.2.4 and luarocks-2.3.0 from your sites or via 
github unzip on your home.
3) First entry on folder for lua5.2.4 unzipped and edit Makefile 
parameter for: INSTALL_TOP= /usr/local/lua-rocks. Execute on same folder 
the command: make linux install (all command without sudo or su).
4) After step 3 entry on folder luarocks-2.3.0 unzipped and execute: 
./configure --prefix=/usr/local/lua-rocks && make build install.

After that steps all functioning perfect on Linux Mint 17.

Best regards,
Hygens

**Comment by Etiene** [comment] 2016-02-22 00:26
Perfect! may I close this issue now? :)

**Comment by Hygens** [comment] 2016-02-22 00:28
Yes. Thank you for your help and support.

**Comment by Etiene** [comment] 2016-02-22 07:24
Yay! :dancers:

**Closed by Etiene** 2016-02-22 07:24 UTC
